name: WSO2 API Manager & Analytic server
description: |
  WSO2 API Manager and Analytic server using the "pattern-2" config from wso2 repo: https://github.com/wso2/docker-apim/tree/master/docker-compose/pattern-2
version: v0.1
category: API
maintainer: Ernest Lau 
projectURL: https://wso2.com/api-management/
